services:
  backend:
    image: ghcr.io/dsgnr/corvin-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./corvin_data:/data
      - ./downloads:/downloads
    environment:
      - TZ=UTC
    restart: unless-stopped

  frontend:
    image: ghcr.io/dsgnr/corvin-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped